const PRODUCTS = [
  {
    product_id: 'PROD001',
    product_name: 'Floral Wrap Midi Dress',
    brand: 'HERE&NOW',
    category: 'Dress',
    price: 1299,
    image_url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=500&fit=crop',
    color: 'Dusty Rose & Ivory',
    material: 'Viscose Crepe',
    available_sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: 'Casual, Brunch, Day Out',
    style_tags: ['floral', 'midi', 'wrap', 'feminine', 'boho', 'summer'],
  },
  {
    product_id: 'PROD002',
    product_name: 'Bandhani Print Cotton Kurti',
    brand: 'BIBA',
    category: 'Kurti',
    price: 999,
    image_url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400&h=500&fit=crop',
    color: 'Indigo Blue & White',
    material: '100% Cotton',
    available_sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    occasion: 'Casual, Office, Festive',
    style_tags: ['ethnic', 'bandhani', 'cotton', 'traditional', 'printed', 'indian'],
  },
  {
    product_id: 'PROD003',
    product_name: 'Kanjivaram Silk Saree',
    brand: 'Kalki Fashion',
    category: 'Saree',
    price: 8499,
    image_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&h=500&fit=crop',
    color: 'Deep Magenta & Gold',
    material: 'Pure Silk',
    available_sizes: ['Free Size'],
    occasion: 'Wedding, Festive, Puja, Ceremony',
    style_tags: ['silk', 'saree', 'traditional', 'wedding', 'festive', 'kanjivaram', 'ethnic'],
  },
  {
    product_id: 'PROD004',
    product_name: 'Oversized Linen Co-ord Set',
    brand: 'MANGO',
    category: 'Co-ord Set',
    price: 3499,
    image_url: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4c0a?w=400&h=500&fit=crop',
    color: 'Sand Beige',
    material: 'Linen Blend',
    available_sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: 'Brunch, Travel, Casual, Weekend',
    style_tags: ['coord', 'linen', 'oversized', 'minimal', 'neutral', 'summer', 'trendy'],
  },
  {
    product_id: 'PROD005',
    product_name: 'High-Rise Straight Fit Jeans',
    brand: 'Levis',
    category: 'Jeans',
    price: 2799,
    image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&h=500&fit=crop',
    color: 'Classic Indigo Blue',
    material: '98% Cotton, 2% Elastane',
    available_sizes: ['24', '26', '28', '30', '32', '34', '36'],
    occasion: 'Casual, College, Work, Weekend',
    style_tags: ['denim', 'jeans', 'high-rise', 'straight', 'classic', 'versatile'],
  },
  {
    product_id: 'PROD006',
    product_name: 'Relaxed Fit Printed Oversized Shirt',
    brand: 'H&M',
    category: 'Top',
    price: 1499,
    image_url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=500&fit=crop',
    color: 'Abstract Teal Print',
    material: 'Viscose',
    available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasion: 'Casual, Beach, Brunch, Travel',
    style_tags: ['oversized', 'shirt', 'printed', 'relaxed', 'street-style', 'summer'],
  },
  {
    product_id: 'PROD007',
    product_name: 'Structured Power Blazer',
    brand: 'AND',
    category: 'Blazer',
    price: 3999,
    image_url: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=400&h=500&fit=crop',
    color: 'Charcoal Grey',
    material: 'Polyester Blend',
    available_sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: 'Office, Formal, Meetings, Evening Out',
    style_tags: ['blazer', 'formal', 'structured', 'power-dressing', 'office', 'sophisticated'],
  },
  {
    product_id: 'PROD008',
    product_name: 'Embroidered Anarkali Suit Set',
    brand: 'W for Woman',
    category: 'Ethnic Wear',
    price: 4299,
    image_url: 'https://images.unsplash.com/photo-1585944285597-e67af9f15c9d?w=400&h=500&fit=crop',
    color: 'Peacock Green & Gold',
    material: 'Art Silk with Embroidery',
    available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasion: 'Festive, Wedding, Party, Eid, Diwali',
    style_tags: ['anarkali', 'ethnic', 'embroidered', 'festive', 'traditional', 'flared', 'occasion-wear'],
  },
];

function getProduct(productId) {
  return PRODUCTS.find((item) => item.product_id === productId) || null;
}

module.exports = { PRODUCTS, getProduct };
