[server]
headless = true
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#ff3e6c"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor = "#282c3f"
font = "sans serif"
